DROP DATABASE IF EXISTS loginApp;
CREATE DATABASE loginApp CHARACTER SET utf8mb4;
USE loginApp;

CREATE TABLE users (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`name` VARCHAR(250) NOT NULL,
`password` VARCHAR(250) NOT NULL ,
`email` VARCHAR(250) NOT NULL,
`username` VARCHAR(250) NOT NULL
);