DROP DATABASE IF EXISTS lol;
CREATE DATABASE lol CHARACTER SET utf8mb4;
USE lol;

CREATE TABLE champ (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`name` VARCHAR(250) NOT NULL,
rol ENUM('Asesino', 'Mago', 'Apoyo') NOT NULL,
difficulty VARCHAR(250) NOT NULL,
`description` text(250) NOT NULL
);

CREATE TABLE users (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`name` VARCHAR(250) NOT NULL,
`password` VARCHAR(250) NOT NULL ,
`email` VARCHAR(250) NOT NULL,
`username` VARCHAR(250) NOT NULL
);